config/routes.rb
Rails.application.routes.draw do
  devise_for :passengers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights,  only: [:index] do
    collection do
      get :search
    end
    resources :tickets, only: [:new, :create]
  end

  resources :tickets, only: [:index, :show,]
  # Defines the root path route ("/")
  root "flights#index"
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  has_many :passengers, through: :tickets, source: :passenger
  has_many :tickets

  after_create :add_flight_code

  def seats_calculator(reserved_seats)
    self.seats = seats - reserved_seats
    self.save
  end

  def add_flight_code
    self.code = "#{departure_airport.id}#{arrival_airport.id}-#{departure_airport.code}-#{arrival_airport.code}-#{id}"
    self.save
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include FlightsConcern

  def index
    @airports = Airport.pluck(:name, :code, :city, :country, :id).map do |name, code, city, country, id|
      ["#{name}, #{code}, #{city}, #{country}", id]
    end
    search_params = params.permit(:departure_airport_id, :arrival_airport_id)
    @required_seats = params[:required_seats]
    @flights = search_result(search_params, params[:start_time], params[:required_seats])
  end

  def search_result(parameters, start_time, required_seats)
    if parameters.empty?
      Flight.where('seats > ?', 0).order(start_time: :asc).limit(12)
    elsif parameters['departure_airport_id'] == parameters['arrival_airport_id']
      find_flights_value_when_depart_equal_arrive(start_time, required_seats)
    else
      find_flights_value_when_depart_not_equal_arrive(parameters, start_time, required_seats)
    end
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
  <li class="card p-1 m-1 bg-light bg-gradient">
    <%= link_to new_flight_ticket_path(flight_id: flight.id, required_seats: @required_seats), class: "text-reset text-decoration-none" do %>
      <h5>
      <small><strong>From </strong></small><%= flight.departure_airport.code %> Airport <small><strong> To </strong></small><%= flight.arrival_airport.code %> Airport
      </h5>
      <p>
        <small><strong>Flies from </strong></small><%= flight.departure_airport.city.upcase %>, <%= flight.departure_airport.country.upcase %><small><strong> Land's in </strong></small><%= flight.arrival_airport.city.upcase %>, <%= flight.arrival_airport.country.upcase %>
      </p>
        <div class="d-flex justify-content-end">
          <p class="text-reset text-decoration-none"><strong>Flies in: </strong><small><%= flight.start_time.strftime("%a, %H:%M, %d %b %Y") %> </small></p>
          <p class="text-reset text-decoration-none mx-1"><strong> Duration: </strong><small><%= flight.duration %> Hrs </small></p>
        </div>
    <% end %>
  </li>

app/views/flights/_flights.html.erb
<ul  class="list-unstyled">
      <% if @flights %>
        <% @flights.each do |flight| %>
          <%= render @flight, flight: flight %>
        <% end %>
      <% else %>
        <h5>NO FLIGHTS FOUND FOR THE GIVEN PARAMETERS!!!<h5>
      <% end %>
  </ul>

app/views/flights/_search_form.html.erb
<%= form_with(url: {controller: "flights", action: "index"}, method: :get, html: {style: 'max-width: 100%; ', class: 'd-flex flex-column align-items-center gap-1 m-1'}) do |f| %>
  <div style="width: 98%" class="d-flex flex-row flex-wrap justify-content-between align-items-between align-self-center">
  <div style="gap: 0.5em !important; margin: 0.5em !important;  max-width: 95%" class="d-flex flex-row ">
    <%= f.label :departure_airport_id, 'Departure Airport' %>
    <%= f.select :departure_airport_id, @airports, {}, { style: 'max-width: 60% !important;' } %>
    </div>
    <div style="gap: 0.5em !important; margin: 0.5em !important; max-width: 95%" class="d-flex flex-row align-items-center align-self-end">
    <%= f.label :arrival_airport_id, 'Arrival Airport' %>
    <%= f.select :arrival_airport_id, @airports, {}, { style: 'max-width: 60% !important;' } %>
    </div>
  </div>

  <div style="max-width: 100%" class="d-flex flex-row flex-wrap justify-content-between">
    <div class="d-flex flex-column flex-wrap">
      <%= f.label :start_time, 'Date' %>
      <%= f.date_field :start_time %>
    </div>

    <div style="max-width: 35%" class="d-flex flex-column">
      <%= f.label :required_seats, 'Seats Required' %>
      <%= f.number_field :required_seats, value: 1 %>
    </div>
  </div>

  <%= f.button 'Search', data: { turbo_frame: "after_form", partial: "flights/flights" }, style: 'width: 50%; align-self: center;', class:"button text-primary bg-light rounded border-1" %>
<% end %>

app/views/flights/index.html.erb
<%# turbo_frame_tag "reserve_ticket" do %>
  <h1 style="margin-left: 1% !important; max-width: 99%">FIND A FLIGHT</h1>
<div style="min-height: 65%;" class="d-flex flex-column gap-1 justify-content-center align-items-center">
  <div style="width: 98% !important; gap: 8px !important;" class="card d-flex flex-column justify-content-center">
    <%= render 'search_form' %>
  </div>
  
    <%= render @flights %>
  <%# end %>
</div>
<%# end %>