config/routes.rb
Rails.application.routes.draw do
  devise_for :passengers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights,  only: [:index] do
    collection do
      get :search
    end
    resources :tickets, only: [:new, :create]
  end

  resources :tickets, only: [:index, :show,]
  # Defines the root path route ("/")
  root "flights#index"
end

app/views/layouts/_nav.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to "Home", root_path, class: "nav-link #{flights_active}", role: "tab", "aria-controls" => "home", "aria-selected" => "false" %>
  </li>
  <% if !passenger_signed_in? %>
    <li class="nav-item" role="presentation">
      <%= button_to "Login", new_passenger_session_path, :method => :get, class: "nav-link #{login_active}", role: "tab", "aria-controls" => "profile", "aria-selected" => "true" %>
    </li>
  <% end %>
  <li class="nav-item" role="presentation">
    <%= link_to "Tickets", tickets_path, class: "nav-link #{tickets_active}", role: "tab", "aria-controls" => "messages", "aria-selected" => "false" %>
  </li>
  <% if passenger_signed_in? %>
      <%= button_to "Logout", destroy_passenger_session_path, :method => :delete, class: "nav-link" %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%; width: 100%">
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="height: 97%; width: 100%">
      <nav style="position: fixed; width: 100%; z-index: 2; top: 0; height: 3.5em; padding: 0.5em;" class="bg-white"><%= render partial: 'layouts/nav' %></nav>
    <main style="padding: 0.25em;" class="d-flex flex-column align-items-center">
      <div class="mt-5">
        <p class="notice"><%= notice %></p>
        <%= turbo_stream_from "ticket_#{@ticket.current_passenger.id}" %>
        <p id="alert" class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/message.html.erb
<p id="alert" class="alert"><%= alert %></p>